server:
  port: 8059
  servlet:
    context-path: /indexing/v1
alphavantage:
  apikey: J22355EMA6H0FCIS
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss
  datasource:
    url: jdbc:mariadb://localhost:3306/ticks
    username: root
    password: r00t
    driver-class-name: org.mariadb.jdbc.Driver
    default-auto-commit: false
    tomcat:
      initial-size: 5
  jpa:
#    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      temp.use_jdbc_metadata_defaults: false
#    hibernate.ddl-auto: create-drop
#    generate-ddl: true
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace